# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7abe8506d682b8b2034bf3b3277909a692d18724d341544df6d968b70da593d52908a7761aaab5f69e080eb01327c3608de62525d846f785c6344c298891a16

test:
  secret_key_base: f3e4fd77f5d114db24dee78f8f061cc4a1e003706ace688c24ad52986e5ee576f40d3d1fab974f924df89974addc545e7061ea224c85d58c2a2154fe3efaa176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
